// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAij0SYoaWHAvjSB4nj3e__XpcLXfQByZw',
    appId: '1:69616214720:web:57fe6f1a81fc47a8734325',
    messagingSenderId: '69616214720',
    projectId: 'fir-flutter-af1c7',
    authDomain: 'fir-flutter-af1c7.firebaseapp.com',
    storageBucket: 'fir-flutter-af1c7.appspot.com',
    measurementId: 'G-EHF2QMBD61',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrJ27xL7c2MGT1geqCyiDO4CU0r_8dRuc',
    appId: '1:69616214720:android:6b1cf24422348e55734325',
    messagingSenderId: '69616214720',
    projectId: 'fir-flutter-af1c7',
    storageBucket: 'fir-flutter-af1c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBJ_CZ3Mp56BOv8JxzJ6uiQmiXNc6yORU',
    appId: '1:69616214720:ios:f17d9c9cd180818b734325',
    messagingSenderId: '69616214720',
    projectId: 'fir-flutter-af1c7',
    storageBucket: 'fir-flutter-af1c7.appspot.com',
    iosClientId: '69616214720-96fuu28tpf087ocfmcln1g4gnb1uqd1c.apps.googleusercontent.com',
    iosBundleId: 'loyd.kim.flutter.firebase.firebasecloudstorage',
  );
}
